# Open Watcom makefile to build SDL2 tests for Win32
# wmake -f Makefile.w32

SYSTEM = nt

INCPATH = -I"$(%WATCOM)/h/nt" -I"$(%WATCOM)/h" -I"../src/video/khronos"

CFLAGS = -bt=nt -d0 -q -bm -5s -fp5 -fpi87 -sg -oteanbmier -ei
CFLAGS+= -wx -wcd=303
CFLAGS+= -DSDL_MAIN_HANDLED
CFLAGS+= -DHAVE_OPENGL
GLLIBS = opengl32.lib

TNSRCS = testnative.c testnativew32.c

!include watcom.mif
