# Open Watcom makefile to build SDL2 tests for OS/2
# wmake -f Makefile.os2

SYSTEM = os2v2

INCPATH = -I"$(%WATCOM)/h/os2" -I"$(%WATCOM)/h"

CFLAGS = -bt=os2 -d0 -q -bm -5s -fp5 -fpi87 -sg -oteanbmier -ei
CFLAGS+= -wx -wcd=303

TNSRCS = testnative.c testnativeos2.c

!include watcom.mif
