site_name: SDL
site_description: Simple Direct Media Layer
docs_dir: docs
site_dir: build/docs
repo_url: https://github.com/libsdl-org/SDL
repo_name: GitHub

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: [c]

markdown_extensions:
  - toc:
      toc_depth: 2

nav:
  - README.md
  - README-android.md
  - README-cmake.md
  - README-directfb.md
  - README-dynapi.md
  - README-emscripten.md
  - README-gesture.md
  - README-git.md
  - README-hg.md
  - README-ios.md
  - README-kmsbsd.md
  - README-linux.md
  - README-macosx.md
  - README.md
  - README-nacl.md
  - README-os2.md
  - README-pandora.md
  - README-platforms.md
  - README-porting.md
  - README-psp.md
  - README-raspberrypi.md
  - README-touch.md
  - README-visualc.md
  - README-wince.md
  - README-windows.md
  - README-winrt.md
