#include "linepoint.vert.sm60.dxil.h"
#include "tri_color.vert.sm60.dxil.h"
#include "tri_texture.vert.sm60.dxil.h"
#include "color.frag.sm60.dxil.h"
#include "texture_rgba.frag.sm60.dxil.h"
#include "texture_rgb.frag.sm60.dxil.h"
