name: Build (OS/2)

on: [push, pull_request]

jobs:
  os2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: open-watcom/setup-watcom@v0
      - name: Build SDL2
        run: |
          wmake -f Makefile.os2
      - name: Build tests
        run: |
          cd test && wmake -f Makefile.os2
          cd ..
      - name: distclean
        run: |
          wmake -f Makefile.os2 distclean
          cd test && wmake -f Makefile.os2 distclean
          cd ..
