name: Build (Sony Playstation Portable)

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  psp:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dependencies
      run: |
        apk update
        apk add cmake gmp mpc1 mpfr4 make pkgconf
    - name: Patch the pspdev toolchain to use -isystem instead of -I
      run: |
        # https://github.com/pspdev/pspsdk/issues/123
        sed -E s/-I/-isystem/g -i $PSPDEV/psp/share/pspdev.cmake
    - name: Configure (CMake)
      run: |
        cmake -S . -B build \
          -Wdeprecated -Wdev -Werror \
          -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake \
          -DSDL_WERROR=ON \
          -DSDL_TESTS=ON \
          -DSDL_INSTALL_TESTS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=prefix
    - name: Build (CMake)
      run: cmake --build build --config Release --verbose
    - name: Install (CMake)
      run: |
        echo "SDL3_DIR=$(pwd)/prefix" >> $GITHUB_ENV
        cmake --install build --config Release
        ( cd prefix; find ) | LC_ALL=C sort -u
    - name: Package (CPack)
      run: |
        cmake --build build/ --config Release --target package
    - name: Verify CMake configuration files
      run: |
        cmake -S cmake/test -B cmake_config_build \
          -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake \
          -DCMAKE_PREFIX_PATH=${{ env.SDL3_DIR }} \
          -DTEST_SHARED=FALSE \
          -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake_config_build --verbose
    - name: Verify sdl3.pc
      run: |
        export CC=psp-gcc
        export LDFLAGS="-L$PSPDEV/lib -L$PSPDEV/psp/lib -L$PSPDEV/psp/sdk/lib"
        export PKG_CONFIG_PATH=${{ env.SDL3_DIR }}/lib/pkgconfig
        cmake/test/test_pkgconfig.sh
    - uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: SDL-psp
        path: build/dist/SDL3*
