name: Build (Sony Playstation Portable)

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  psp:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dependencies
      run: |
        apk update
        apk add cmake gmp mpc1 mpfr4 make pkgconf
    - name: Pollute PSP SDK with "bad" SDL headers
      run: |
        # Create "bad" SDL headers in the PSP SDK.
        # SDL sources should not use these. 
        infixes=". psp psp/sdk"
        for infix in $infixes; do
          directory="$PSPDEV/$infix/include/SDL3"
          echo "Creating directory $directory"
          mkdir -p "$directory"
          for include in include/SDL3/*.h; do
            dest="$PSPDEV/$infix/include/SDL3/$(basename "$include")"
            echo "Creating $dest"
            echo '#error "System SDL headers must not be used by build system"' >"$dest"
          done
        done
    - name: Configure (CMake)
      run: |
        cmake -S . -B build \
          -Wdeprecated -Wdev -Werror \
          -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake \
          -DSDL_WERROR=ON \
          -DSDL_TESTS=ON \
          -DSDL_INSTALL_TESTS=ON \
          -DSDL_DISABLE_INSTALL_DOCS=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=prefix
    - name: Build (CMake)
      run: cmake --build build --config Release --verbose
    - name: Install (CMake)
      run: |
        echo "SDL3_DIR=$(pwd)/prefix" >> $GITHUB_ENV
        cmake --install build --config Release
        ( cd prefix; find ) | LC_ALL=C sort -u
    - name: Package (CPack)
      run: |
        cmake --build build/ --config Release --target package
    - name: Verify CMake configuration files
      run: |
        cmake -S cmake/test -B cmake_config_build \
          -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake \
          -DCMAKE_PREFIX_PATH=${{ env.SDL3_DIR }} \
          -DTEST_SHARED=FALSE \
          -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake_config_build --verbose
    - name: Verify sdl3.pc
      run: |
        export CC=psp-gcc
        export LDFLAGS="-L$PSPDEV/lib -L$PSPDEV/psp/lib -L$PSPDEV/psp/sdk/lib"
        export PKG_CONFIG_PATH=${{ env.SDL3_DIR }}/lib/pkgconfig
        cmake/test/test_pkgconfig.sh
    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: SDL-psp
        path: build/dist/SDL3*
