name: Build (visionOS)

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer

jobs:
  Build:
    name: visionOS
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: |
          cmake -B build -GXcode -DCMAKE_SYSTEM_NAME=visionOS
      - name: Build
        run: |
          cmake --build build
